### ISSUE TITLE
How dependent is this on Domino's Japan?

### ISSUE THREAD

**Issue by pschfr** [inket/dominosjp#1]
I live in the US, and obviously have Domino's here as well, what parts of the code are Japan-dependent and do you think I could easily switch this to work in the US?

**Comment by inket** [comment]
IMO, it's heavily dependent on the Japanese version of the website which is completely different from the US counterpart. The Japanese version of the website was independently developed so there's nothing shared.

But also, the models on this gem aren't really [pizza source]-agnostic as it wasn't made with other versions in mind. Making them so would be the same amount of work as say, adding Pizza Hut support.

This was made because there weren't any alternatives in Japan.

The US has plenty it seems. May I suggest:
https://www.reddit.com/r/linux/comments/3n7rkz/is_there_any_working_way_to_order_pizza_from_the/
https://github.com/RIAEvangelist/node-dominos-pizza-api

**Comment by pschfr** [comment]
Awesome, thank you! I'll take a look.
